export const HOUSEHOLD_START = 'HOUSEHOLD_START';
export const HOUSEHOLD_SUCCESS = 'HOUSEHOLD_SUCCESS';
export const HOUSEHOLD_FAIL = 'HOUSEHOLD_FAIL';
export const HOUSEHOLD_CLEAR = 'HOUSEHOLD_CLEAR';