# Generated by Django 4.0.5 on 2022-07-21 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('household', '0001_initial'),
        ('devices', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereading',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.household'),
        ),
        migrations.AddField(
            model_name='devicereading',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_category', to='devices.category'),
        ),
        migrations.AddField(
            model_name='device',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.household'),
        ),
        migrations.AddField(
            model_name='category',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.household'),
        ),
    ]
