# Generated by Django 4.0.5 on 2022-08-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_devicereading_device_gassensorreading_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='category',
        ),
        migrations.RemoveField(
            model_name='device',
            name='household',
        ),
        migrations.AlterField(
            model_name='gassensorreading',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='proximitysensorreading',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
