# Generated by Django 4.0.5 on 2022-09-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_device_category_remove_device_household_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gassensorreading',
            name='status',
            field=models.CharField(default='High', max_length=10),
            preserve_default=False,
        ),
    ]
